name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install root deps
        run: npm install

      - name: Install server deps
        run: cd server && npm install

      - name: Install client deps
        run: cd client && npm install

      - name: Install contracts deps
        run: cd contracts && npm install

      - name: Lint/Build client
        run: cd client && npm run build --if-present

      - name: Test server
        run: cd server && npm test --if-present

      - name: Test contracts
        run: cd contracts && npx hardhat compile && npm test --if-present
