version: '3.9'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agrikonbit
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ../
      dockerfile: docker/server.Dockerfile
    env_file:
      - ../server/env.example
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: agrikonbit
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - db
    ports:
      - "5000:5000"

  client:
    build:
      context: ../
      dockerfile: docker/client.Dockerfile
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    depends_on:
      - server
    ports:
      - "3000:3000"

volumes:
  db_data:
